### ISSUE TITLE
为啥不用OC嘞

### ISSUE THREAD

**Issue by iSuAbner** [geemaple/leetcode#2]
如题

**Comment by geemaple** [comment]
OC是一门不错的语言，尤其是近10年来，移动端发展比较迅猛，OC进入开发者的视野。其语法表意，易于学习和普及，受到不少年轻人的喜爱。但是对于算法，我认为OC有以下缺点。可以用swift替代，而且Tensorflow也把swift作为支持语言之一。

1. 使用的OJ(Online Judge)不支持该语言
2. OC命名过于冗长，不易记忆，算法一个重要场景是面试，要白板上书写
3. OC使用繁琐，对于简单的数字数组，还要包一层Number
4. OC缺少一些内置数据容器，例如，双端队列, 优先队列等。同样原因也不推荐用C写
5. OC算法领域使用场景比较狭窄，不便于网络交流

个人推荐的语言依次为Python，C++，Java，Swift和Javascript

**Comment by iSuAbner** [comment]
嗯嗯  现在开始尝试用Python写了。
